version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto    
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      
    ports:
      - 1883:1883
      - 9001:9001
    networks:
        vpcbr:
        ipv4_address: 127.0.0.1
  websocket-mqtt:
    image: websocket-mqtt
    container_name: websocket-mqtt
    volumes: ./app:/app
    networks:
      vpcbr:
      ipv4_address: 127.0.1.1
    depends_on:
      - mosquitto
  restart: unless-stopped
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 127.0.0.1/24